# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: blank # the website title (if blank, full name will be used instead)
first_name: Scott
middle_name: Lee
last_name: Chua 🇵🇭
email: scottleechua@gmail.com
description: Econs | Comics | Puzzles
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme. Read the <a href="/privacy/">Privacy Policy</a>.
keywords:

lang: en
icon: # the emoji used as the favicon
url:  https://scottleechua.com
baseurl: # the subpath of your site, e.g. /blog/ (LEAVE EMPTY FOR ROOT SITE)
last_updated: false # set to true if you want to display last updated in the footer
impressum_path:  # set to path to include impressum link in the footer, use the same path as permalink in a page, helps to conform with EU GDPR

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

# Dimensions
max_width: 800px

# TODO: add layout settings (single page vs. multi-page)

# -----------------------------------------------------------------------------
# Open Graph & Schema.org
# -----------------------------------------------------------------------------
# Display links to the page with a preview object on social media.
serve_og_meta: true # Include Open Graph meta tags in the HTML head
serve_schema_org: false # Include Schema.org in the HTML head
og_image: profile-picture.png # The site-wide (default for all links) Open Graph preview image

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------

github_username: scottleechua # your GitHub user name
#gitlab_username: # your GitLab user name
#twitter_username: # your Twitter handle
linkedin_username: # your LinkedIn user name
scholar_userid: GJBprlAAAAAJ # your Google Scholar ID
#orcid_id: # your ORCID ID
#medium_username: # your Medium username
#quora_username: # your Quora username
#publons_id: # your ID on Publons
#research_gate_profile: # your profile on ResearchGate
#blogger_url: # your blogger URL
#work_url: # work page URL
#keybase_username: # your keybase user name
#wikidata_id: # your wikidata id
#dblp_url: # your DBLP profile url
#stackoverflow_id: #your stackoverflow id


contact_note: # > You can even add a little note about which of these is the best way to reach you.

# panelbear_analytics: XXXXXXXXX # panelbear analytics site ID
# plausible_analytics: 
# google_site_verification:  # your google-site-verification ID (Google Search Console)
# bing_site_verification:  # out your bing-site-verification ID (Bing Webmaster)


# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------

blog_name: Blog
blog_nav_title: blog # your blog must have a title for it to be displayed in the nav bar
# blog_description: 
permalink: /blog/:title/

# Pagination
pagination:
  enabled: true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

news_limit: 5

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Markdown and syntax highlight
markdown: kramdown
highlighter: rouge
highlight_theme: github  # https://github.com/jwarby/jekyll-pygments-themes
highlight_theme_light: github  # https://github.com/jwarby/jekyll-pygments-themes
highlight_theme_dark: native  # https://github.com/jwarby/jekyll-pygments-themes
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# Includes & excludes
include: ['_pages']
exclude:
  - bin
  - Gemfile
  - Gemfile.lock
  - vendor
keep_files:
  - CNAME
  - .nojekyll
  - .git

# Plug-ins
plugins:
  - jekyll-email-protect
  - jekyll-github-metadata
  - jekyll-paginate-v2
  - jekyll/scholar
  - jemoji
  - jekyll-target-blank
  - jekyll-minifier
  - jekyll-sitemap

# jekyll-target-blank settings (https://github.com/keithmifsud/jekyll-target-blank)
target-blank:
    noreferrer: false

# Extras
github: [metadata]

# Sitemap settings
defaults:
  - scope:
      path: "assets/**/*.*"
    values:
      sitemap: false

# Jekyll Minifier

jekyll-minifier:
  exclude: ['robots.txt']
  uglifier_args:
    harmony: true

# -----------------------------------------------------------------------------
# Jekyll Scholar
# -----------------------------------------------------------------------------

scholar:

  last_name: Chua
  first_name: [Scott, S., S.L.]

  style: apa
  locale: en

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"
  
filtered_bibtex_keywords: [abbr, abstract, arxiv, bibtex_show, html, pdf, selected, supp, blog, code, poster, slides, website] # Filter out certain bibtex entry keywords used internally from the bib output


# -----------------------------------------------------------------------------
# Optional Features
# -----------------------------------------------------------------------------

enable_plausible_analytics: false
enable_google_verification: false  # enables google site verification
enable_bing_verification:   false  # enables bing site verification
enable_masonry:             true
enable_math:                true
enable_darkmode:            false
enable_navbar_social:       false
enable_project_categories:  true   # enables categorization of projects into
                                   # multiple categories

# -----------------------------------------------------------------------------
# Library versions
# -----------------------------------------------------------------------------

academicons:
  version: "1.9.1"
  integrity: "sha256-i1+4qU2G2860dGGIOJscdC30s9beBXjFfzjWLjBRsBg="
bootstrap:
  version: "4.6.1"
  integrity:
    css: "sha256-DF7Zhf293AJxJNTmh5zhoYYIMs2oXitRfBjY+9L//AY="
    js: "sha256-SyTu6CwrfOhaznYZPoolVw2rxoY7lKYKQvqbtqN93HI="
fontawesome:
  version: "5.15.4"
  integrity: "sha256-mUZM63G8m73Mcidfrv5E+Y61y7a12O5mW4ezU3bxqW4="
jquery:
  version: "3.6.0"
  integrity: "sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
katex:
  version: "0.16.0"
  integrity:
    css: "sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC"
    js: "sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja"
    autorender: "sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR"
masonry:
  version: "4.2.2"
  integrity: "sha256-Nn1q/fx0H7SNLZMQ5Hw5JLaTRZp0yILA/FRexe19VdI="
mdb:
  version: "4.20.0"
  integrity:
    css: "sha256-jpjYvU3G3N6nrrBwXJoVEYI/0zw8htfFnhT9ljN3JJw="
    js: "sha256-NdbiivsvWt7VYCt6hYNT3h/th9vSTL4EDWeGs5SN3DA="
popper:
  version: "2.11.2"
  integrity: "sha256-l/1pMF/+J4TThfgARS6KwWrk/egwuVvhRzfLAMQ6Ds4="